name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint and Format
        run: |
          pip install flake8 black isort
          flake8 src/
          black --check src/
          isort --check-only src/

      - name: Run tests
        run: |
          pip install pytest coverage
          pytest --cov=src tests/

      - name: Build Docker image
        run: |
          docker build -t src:latest .